package com.example.hasibati;
import android.accessibilityservice.AccessibilityService;import android.view.accessibility.AccessibilityEvent;import android.view.accessibility.AccessibilityNodeInfo;import android.os.*;import java.util.*;
public class CommandAccessibilityService extends AccessibilityService{
 public static volatile String pendingExpression="",pendingSearch=""; Handler h=new Handler(Looper.getMainLooper()); boolean busy=false;
 public void onAccessibilityEvent(AccessibilityEvent e){if((pendingExpression.isEmpty()&&pendingSearch.isEmpty())||busy)return;busy=true;h.post(new Runnable(){int tries=0;public void run(){tries++;AccessibilityNodeInfo root=getRootInActiveWindow();if(root!=null){if(!pendingExpression.isEmpty()){AccessibilityNodeInfo edit=findEdit(root);if(edit!=null){Bundle b=new Bundle();b.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,pendingExpression);edit.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,b);String done=pendingExpression;pendingExpression="";h.postDelayed(()->{AccessibilityNodeInfo r=getRootInActiveWindow();if(r!=null)clickEquals(r);},350);busy=false;return;}}else if(!pendingSearch.isEmpty()){AccessibilityNodeInfo edit=findEdit(root);if(edit==null)clickSearch(root);else{Bundle b=new Bundle();b.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,pendingSearch);edit.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,b);pendingSearch="";h.postDelayed(()->{AccessibilityNodeInfo r=getRootInActiveWindow();if(r!=null)clickSearch(r);},450);busy=false;return;}}}if(tries<18)h.postDelayed(this,350);else{busy=false;}}});}
 void clickEquals(AccessibilityNodeInfo n){if(n==null)return;CharSequence t=n.getText(),d=n.getContentDescription();String s=(t==null?"":t.toString())+" "+(d==null?"":d.toString()).toLowerCase(Locale.ROOT);if(s.trim().equals("=")||s.contains("equals")||s.contains("يساوي")){if(n.isClickable())n.performAction(AccessibilityNodeInfo.ACTION_CLICK);else{for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo c=n.getChild(i);if(c!=null)clickEquals(c);}}return;}for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo c=n.getChild(i);if(c!=null)clickEquals(c);}}
 void clickSearch(AccessibilityNodeInfo n){if(n==null)return;CharSequence t=n.getText(),d=n.getContentDescription();String s=((t==null?"":t.toString())+" "+(d==null?"":d.toString())).toLowerCase(Locale.ROOT);if(s.contains("search")||s.contains("بحث")||s.equals("🔍")){if(n.isClickable())n.performAction(AccessibilityNodeInfo.ACTION_CLICK);return;}for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo c=n.getChild(i);if(c!=null)clickSearch(c);}}
 AccessibilityNodeInfo findEdit(AccessibilityNodeInfo n){if(n.isEditable())return n;for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo c=n.getChild(i);if(c!=null){AccessibilityNodeInfo x=findEdit(c);if(x!=null)return x;}}return null;}
 public void onInterrupt(){} public void onDestroy(){h.removeCallbacksAndMessages(null);super.onDestroy();}
}
