package com.example.hasibati;
import android.accessibilityservice.AccessibilityService;import android.view.accessibility.AccessibilityEvent;import android.view.accessibility.AccessibilityNodeInfo;import android.os.*;import java.util.*;
public class CommandAccessibilityService extends AccessibilityService{
 public static volatile String pendingExpression="",pendingSearch=""; Handler h=new Handler(Looper.getMainLooper()); boolean running=false;
 public void onAccessibilityEvent(AccessibilityEvent e){if(running)return;if(pendingExpression.isEmpty()&&pendingSearch.isEmpty())return;running=true;h.postDelayed(()->work(),700);}
 void work(){AccessibilityNodeInfo root=getRootInActiveWindow();if(root==null){retry();return;}if(!pendingExpression.isEmpty()){String x=pendingExpression;pendingExpression="";typeKeys(x,0);return;}if(!pendingSearch.isEmpty()){AccessibilityNodeInfo edit=findEdit(root);if(edit!=null){setText(edit,pendingSearch);h.postDelayed(()->submitSearch(getRootInActiveWindow()),650);pendingSearch="";running=false;}else{clickSearch(root);retry();}}}
 void typeKeys(String x,int i){if(i>=x.length()){h.postDelayed(()->{clickEquals(getRootInActiveWindow());running=false;},300);return;}AccessibilityNodeInfo root=getRootInActiveWindow();if(root==null){h.postDelayed(()->typeKeys(x,i),350);return;}String key=String.valueOf(x.charAt(i));if(key.equals("*"))key="×";if(key.equals("/"))key="÷";if(key.equals("-"))key="−";AccessibilityNodeInfo n=findKey(root,key);if(n!=null){n.performAction(AccessibilityNodeInfo.ACTION_CLICK);h.postDelayed(()->typeKeys(x,i+1),170);}else if(i==0){AccessibilityNodeInfo edit=findEdit(root);if(edit!=null){setText(edit,x);h.postDelayed(()->{clickEquals(getRootInActiveWindow());running=false;},450);}else{h.postDelayed(()->typeKeys(x,i),350);}}else{h.postDelayed(()->typeKeys(x,i),350);}}
 void submitSearch(AccessibilityNodeInfo root){if(root==null)return;AccessibilityNodeInfo edit=findEdit(root);if(edit!=null)edit.performAction(0x00400000);h.postDelayed(()->clickSearch(getRootInActiveWindow()),180);}\n void setText(AccessibilityNodeInfo n,String s){Bundle b=new Bundle();b.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,s);n.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,b);}
 void retry(){h.postDelayed(()->{running=false;if(!pendingExpression.isEmpty()||!pendingSearch.isEmpty())work();},400);}
 AccessibilityNodeInfo findKey(AccessibilityNodeInfo n,String key){if(n==null)return null;String t=n.getText()==null?"":n.getText().toString().trim();String d=n.getContentDescription()==null?"":n.getContentDescription().toString().trim().toLowerCase(Locale.ROOT);if((t.equals(key)||d.equals(key)||(key.equals("−")&&(t.equals("-")||t.equals("−")||d.contains("minus")||d.contains("ناقص")||d.contains("طرح")))||(key.equals("+")&&(d.contains("plus")||d.contains("جمع")||t.equals("+")))||(key.equals("×")&&(t.equals("x")||d.contains("multiply")||d.contains("ضرب")))||(key.equals("÷")&&(t.equals("/")||d.contains("divide")||d.contains("قسمة"))))&&(n.isClickable()||n.isFocusable()))return n;for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo z=findKey(n.getChild(i),key);if(z!=null)return z;}return null;}
 void clickEquals(AccessibilityNodeInfo n){if(n==null)return;String t=(n.getText()==null?"":n.getText().toString().trim()),d=(n.getContentDescription()==null?"":n.getContentDescription().toString().toLowerCase(Locale.ROOT));if((t.equals("=")||d.contains("equals")||d.contains("يساوي"))&&n.isClickable()){n.performAction(AccessibilityNodeInfo.ACTION_CLICK);return;}for(int i=0;i<n.getChildCount();i++)clickEquals(n.getChild(i));}
 void clickSearch(AccessibilityNodeInfo n){if(n==null)return;String s=((n.getText()==null?"":n.getText().toString())+" "+(n.getContentDescription()==null?"":n.getContentDescription().toString())).toLowerCase(Locale.ROOT);if((s.contains("search")||s.contains("بحث"))&&n.isClickable()){n.performAction(AccessibilityNodeInfo.ACTION_CLICK);return;}for(int i=0;i<n.getChildCount();i++)clickSearch(n.getChild(i));}
 AccessibilityNodeInfo findEdit(AccessibilityNodeInfo n){if(n==null)return null;if(n.isEditable())return n;for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo z=findEdit(n.getChild(i));if(z!=null)return z;}return null;}
 public void onInterrupt(){}public void onDestroy(){h.removeCallbacksAndMessages(null);super.onDestroy();}
}