package com.example.hasibati;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.provider.Settings;import android.speech.tts.TextToSpeech;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import java.util.*;
public class MainActivity extends Activity implements TextToSpeech.OnInitListener{
 EditText command;TextView result;TextToSpeech tts;boolean advanced=false;int blue=Color.rgb(72,116,236);
 public void onCreate(Bundle b){super.onCreate(b);tts=new TextToSpeech(this,this);ui();}
 TextView tv(String s,int n){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(n);return v;}
 GradientDrawable bg(int color){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(18);return g;}
 void ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,28,24,18);r.setBackgroundColor(Color.rgb(8,16,29));TextView h=tv("نفّذ",32);h.setTypeface(null,1);h.setGravity(Gravity.RIGHT);r.addView(h,new LinearLayout.LayoutParams(-1,58));TextView sub=tv("مساعد محلي للتطبيقات والحساب",16);sub.setTextColor(Color.rgb(170,185,210));sub.setGravity(Gravity.RIGHT);r.addView(sub,new LinearLayout.LayoutParams(-1,40));LinearLayout modes=new LinearLayout(this);Button basic=new Button(this);basic.setText("أساسي محلي");Button adv=new Button(this);adv.setText("متقدم محلي");for(Button b:new Button[]{basic,adv}){b.setTextSize(14);b.setTextColor(Color.WHITE);b.setMinHeight(0);b.setPadding(2,0,2,0);}basic.setBackground(bg(Color.rgb(35,55,90)));adv.setBackground(bg(Color.rgb(35,55,90)));modes.addView(basic,new LinearLayout.LayoutParams(0,58,1));modes.addView(adv,new LinearLayout.LayoutParams(0,58,1));r.addView(modes);command=new EditText(this);command.setHint("مثال: افتح الحاسبة واحسب 500 - 42");command.setTextColor(Color.WHITE);command.setHintTextColor(Color.GRAY);command.setTextSize(17);command.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);command.setSingleLine(true);command.setImeOptions(EditorInfo.IME_ACTION_DONE);r.addView(command,new LinearLayout.LayoutParams(-1,68));Button run=new Button(this);run.setText("تنفيذ الأمر");run.setTextSize(18);run.setTextColor(Color.WHITE);run.setMinHeight(0);run.setBackground(bg(blue));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,62);rp.topMargin=16;r.addView(run,rp);result=tv("الوضع الأساسي المحلي جاهز",18);result.setTextColor(Color.rgb(205,215,235));result.setGravity(Gravity.RIGHT);result.setPadding(0,26,0,0);r.addView(result,new LinearLayout.LayoutParams(-1,0,1));TextView foot=tv("المتقدم المحلي: ينفذ خطوات داخل التطبيقات بعد تفعيل إمكانية الوصول.",14);foot.setTextColor(Color.GRAY);foot.setGravity(Gravity.RIGHT);r.addView(foot,new LinearLayout.LayoutParams(-1,72));basic.setOnClickListener(v->{advanced=false;result.setText("الوضع الأساسي المحلي");});adv.setOnClickListener(v->{advanced=true;result.setText("الوضع المتقدم المحلي");});run.setOnClickListener(v->execute());command.setOnEditorActionListener((v,a,e)->{execute();return true;});setContentView(r);}
 void say(String s){result.setText(s);if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"answer");}
 void execute(){String q=command.getText().toString().trim();if(q.isEmpty()){say("اكتب أمراً أولاً");return;}String a=q.toLowerCase(Locale.ROOT);if(advanced&&a.contains("الحاسبة")&&(a.contains("احسب")||a.matches(".*[0-9].*[+×÷*/-].*[0-9].*"))){CommandAccessibilityService.pendingExpression=a.replaceAll("[^0-9+\\-*/().]","");open(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_APP_CALCULATOR),"سأفتح الحاسبة وأكتب العملية");return;}if(a.contains("المعرض")||a.contains("الصور")||a.contains("معرض")){openGallery();return;}if(a.contains("يوتيوب")||a.contains("youtube")){openPackage("com.google.android.youtube","يوتيوب");return;}if(a.contains("ام اكس")||a.contains("mx player")||a.contains("مشغل إم اكس")||a.contains("مشغل الوسائط")){openPackage("com.mxtech.videoplayer.ad","مشغل MX Player");return;}if(a.contains("احسب")||a.matches(".*[0-9].*[+×÷*/-].*[0-9].*")){try{double n=eval(a.replaceAll("[^0-9+\\-*/().]","")+"");say("الناتج هو "+((n==(long)n)?String.valueOf((long)n):String.valueOf(n)));return;}catch(Exception e){say("لم أستطع قراءة العملية");return;}}if(a.contains("الحاسبة")||a.contains("حاسبة")){open(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_APP_CALCULATOR),"سأفتح الحاسبة");return;}if(a.contains("الملفات")||a.contains("ملف")){open(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),"سأفتح الملفات");return;}if(a.contains("الإعدادات")||a.contains("الاعدادات")){open(new Intent(Settings.ACTION_SETTINGS),"سأفتح الإعدادات");return;}if(a.startsWith("افتح")||a.startsWith("شغل")){launchNamedApp(a);return;}say("لم أفهم الأمر. جرّب: افتح المعرض، افتح يوتيوب، افتح MX Player، أو احسب 500 - 42");}
 void openGallery(){Intent i=new Intent(Intent.ACTION_MAIN);i.addCategory(Intent.CATEGORY_APP_GALLERY);try{startActivity(i);say("سأفتح المعرض");}catch(Exception e){open(new Intent(Intent.ACTION_VIEW).setType("image/*"),"سأفتح الصور");}}
 void openPackage(String pkg,String name){Intent i=getPackageManager().getLaunchIntentForPackage(pkg);if(i==null){say("لم أجد تطبيق "+name+" مثبتاً");return;}open(i,"سأفتح "+name);}
 void launchNamedApp(String q){String wanted=q.replace("افتح ","").replace("شغل ","").trim();for(ApplicationInfo x:getPackageManager().getInstalledApplications(PackageManager.GET_META_DATA)){String n=getPackageManager().getApplicationLabel(x).toString();if(wanted.contains(n.toLowerCase(Locale.ROOT))||n.toLowerCase(Locale.ROOT).contains(wanted)){Intent i=getPackageManager().getLaunchIntentForPackage(x.packageName);if(i!=null){open(i,"سأفتح "+n);return;}}}say("لم أجد التطبيق باسم "+wanted);}
 void open(Intent i,String m){try{startActivity(i);say(m);}catch(Exception e){say("لا يوجد تطبيق مناسب لهذا الأمر");}}
 double eval(String s){return new Object(){int p=-1,c;void n(){c=++p<s.length()?s.charAt(p):-1;}boolean eat(int x){while(c==' ')n();if(c==x){n();return true;}return false;}double parse(){n();double v=expr();if(p<s.length())throw new RuntimeException();return v;}double expr(){double v=term();for(;;){if(eat('+'))v+=term();else if(eat('-'))v-=term();else return v;}}double term(){double v=factor();for(;;){if(eat('*'))v*=factor();else if(eat('/'))v/=factor();else return v;}}double factor(){if(eat('+'))return factor();if(eat('-'))return -factor();int st=p;while((c>='0'&&c<='9')||c=='.')n();return Double.parseDouble(s.substring(st,p));}}.parse();}
 public void onInit(int s){if(s==TextToSpeech.SUCCESS)tts.setLanguage(new Locale("ar"));}protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
