package com.example.hasibati;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.graphics.Color;import android.provider.Settings;import android.speech.tts.TextToSpeech;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import java.util.*;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener{
 EditText command;TextView result;TextToSpeech tts;boolean online=false;int blue=Color.rgb(77,125,244);
 @Override public void onCreate(Bundle b){super.onCreate(b);tts=new TextToSpeech(this,this);buildUi();}
 TextView tv(String s,int n){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(n);return v;}
 void buildUi(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(26,30,26,20);r.setBackgroundColor(Color.rgb(10,18,32));TextView title=tv("نفّذ",30);title.setTypeface(null,1);r.addView(title,new LinearLayout.LayoutParams(-1,58));TextView sub=tv("مساعد أوامر للتطبيقات والحساب",15);sub.setTextColor(Color.LTGRAY);r.addView(sub,new LinearLayout.LayoutParams(-1,40));
  LinearLayout modes=new LinearLayout(this);Button local=new Button(this);local.setText("بدون إنترنت");Button net=new Button(this);net.setText("بالإنترنت");modes.addView(local,new LinearLayout.LayoutParams(0,58,1));modes.addView(net,new LinearLayout.LayoutParams(0,58,1));r.addView(modes);command=new EditText(this);command.setHint("اكتب: افتح الحاسبة واحسب 500 - 42");command.setTextColor(Color.WHITE);command.setHintTextColor(Color.GRAY);command.setTextSize(17);command.setSingleLine(true);command.setImeOptions(EditorInfo.IME_ACTION_DONE);r.addView(command,new LinearLayout.LayoutParams(-1,68));Button run=new Button(this);run.setText("تنفيذ الأمر");run.setTextColor(Color.WHITE);run.setBackgroundColor(blue);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,62);rp.topMargin=14;r.addView(run,rp);result=tv("الوضع المحلي: جاهز",17);result.setTextColor(Color.rgb(190,205,230));result.setPadding(0,25,0,0);r.addView(result,new LinearLayout.LayoutParams(-1,0,1));TextView ex=tv("محلي: فتح التطبيقات المثبتة، الحساب، الملفات، الإعدادات\nإنترنت: إرسال الأمر لخدمة المساعد المتصلة (يحتاج إعداد الاتصال)",14);ex.setTextColor(Color.GRAY);r.addView(ex,new LinearLayout.LayoutParams(-1,100));local.setOnClickListener(v->{online=false;result.setText("الوضع المحلي بدون إنترنت");});net.setOnClickListener(v->{online=true;result.setText("الوضع المتصل بالإنترنت");});run.setOnClickListener(v->execute());command.setOnEditorActionListener((v,a,e)->{execute();return true;});setContentView(r);}
 void say(String s){result.setText(s);if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"answer");}
 void execute(){String q=command.getText().toString().trim();if(q.isEmpty()){say("اكتب أمراً أولاً");return;}if(online){say("الوضع المتصل جاهز، اربط خدمة الذكاء الاصطناعي لتنفيذ الأوامر العامة");return;}String a=q.toLowerCase(Locale.ROOT);if(a.contains("احسب")||a.matches(".*[0-9].*[+×÷*/-].*[0-9].*")){String x=a.replaceAll("[^0-9+\\-*/().]","");try{double n=eval(x);say("الناتج هو "+((n==(long)n)?String.valueOf((long)n):String.valueOf(n)));return;}catch(Exception e){say("لم أستطع قراءة العملية");return;}}if(a.contains("الحاسبة")||a.contains("حاسبة")){open(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_APP_CALCULATOR),"سأفتح الحاسبة");return;}if(a.contains("الملفات")||a.contains("ملف")){open(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),"سأفتح الملفات");return;}if(a.contains("الإعدادات")||a.contains("الاعدادات")){open(new Intent(Settings.ACTION_SETTINGS),"سأفتح الإعدادات");return;}if(a.contains("شغل")||a.contains("أغنية")||a.contains("اغنية")||a.contains("مشغل")||a.contains("mx")){Intent i=getPackageManager().getLaunchIntentForPackage("com.mxtech.videoplayer.ad");if(i==null)i=new Intent(Intent.ACTION_VIEW).setType("audio/*");open(i,"سأفتح مشغل الوسائط");return;}launchNamedApp(a);}
 void launchNamedApp(String query){List<ApplicationInfo> apps=getPackageManager().getInstalledApplications(PackageManager.GET_META_DATA);for(ApplicationInfo x:apps){String label=getPackageManager().getApplicationLabel(x).toString();if(query.contains(label.toLowerCase(Locale.ROOT))||label.toLowerCase(Locale.ROOT).contains(query.replace("افتح ","").trim())){Intent i=getPackageManager().getLaunchIntentForPackage(x.packageName);if(i!=null){open(i,"سأفتح "+label);return;}}}say("لم أجد تطبيقاً بهذا الاسم في هاتفك");}
 void open(Intent i,String msg){try{startActivity(i);say(msg);}catch(Exception e){say("لا يوجد تطبيق مناسب لهذا الأمر");}}
 double eval(String s){return new Object(){int p=-1,c;void n(){c=++p<s.length()?s.charAt(p):-1;}boolean eat(int x){while(c==' ')n();if(c==x){n();return true;}return false;}double parse(){n();double v=expr();if(p<s.length())throw new RuntimeException();return v;}double expr(){double v=term();for(;;){if(eat('+'))v+=term();else if(eat('-'))v-=term();else return v;}}double term(){double v=factor();for(;;){if(eat('*'))v*=factor();else if(eat('/'))v/=factor();else return v;}}double factor(){if(eat('+'))return factor();if(eat('-'))return -factor();double v;int st=p;if(eat('(')){v=expr();eat(')');}else{while((c>='0'&&c<='9')||c=='.')n();v=Double.parseDouble(s.substring(st,p));}return v;}}.parse();}
 @Override public void onInit(int s){if(s==TextToSpeech.SUCCESS)tts.setLanguage(new Locale("ar"));}@Override protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
