package com.example.hasibati;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.provider.Settings;import android.speech.tts.TextToSpeech;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import java.util.*;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener {
 EditText command; TextView result; TextToSpeech tts; int blue=Color.rgb(77,125,244);
 @Override public void onCreate(Bundle b){super.onCreate(b);tts=new TextToSpeech(this,this);buildUi();}
 TextView tv(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(size);return v;}
 void buildUi(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,36,28,24);root.setBackgroundColor(Color.rgb(10,18,32));TextView title=tv("نفّذ",30);title.setTypeface(null,1);root.addView(title,new LinearLayout.LayoutParams(-1,60));TextView hint=tv("اكتب أمرك وسأنفذه وأقرأ النتيجة",16);hint.setTextColor(Color.LTGRAY);root.addView(hint,new LinearLayout.LayoutParams(-1,60));command=new EditText(this);command.setHint("مثال: احسب 500 + 25");command.setTextColor(Color.WHITE);command.setHintTextColor(Color.GRAY);command.setTextSize(18);command.setSingleLine(true);command.setImeOptions(EditorInfo.IME_ACTION_DONE);command.setPadding(22,4,22,4);root.addView(command,new LinearLayout.LayoutParams(-1,64));Button run=new Button(this);run.setText("تنفيذ");run.setTextSize(18);run.setTextColor(Color.WHITE);run.setBackgroundColor(blue);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,62);bp.topMargin=18;root.addView(run,bp);result=tv("جاهز لاستقبال أمرك",18);result.setTextColor(Color.rgb(190,205,230));result.setPadding(0,30,0,0);root.addView(result,new LinearLayout.LayoutParams(-1,0,1));TextView examples=tv("أمثلة:\n• احسب 500 + 25\n• افتح الحاسبة\n• افتح الملفات\n• شغل الأغاني\n• ثبّت اللعبة من ملف APK",15);examples.setTextColor(Color.GRAY);root.addView(examples,new LinearLayout.LayoutParams(-1,150));View.OnClickListener l=v->execute();run.setOnClickListener(l);command.setOnEditorActionListener((v,a,e)->{execute();return true;});setContentView(root);}
 void say(String s){result.setText(s);if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"answer");}
 void execute(){String q=command.getText().toString().trim();if(q.isEmpty()){say("اكتب أمراً أولاً");return;}String a=q.toLowerCase(Locale.ROOT);if(a.contains("احسب")||a.matches(".*[0-9].*[+×÷*/-].*[0-9].*")){String x=a.replaceAll("[^0-9+\\-*/().]","");try{double n=eval(x);String z=(n==(long)n)?String.valueOf((long)n):String.valueOf(n);say("الناتج هو "+z);return;}catch(Exception e){say("لم أستطع قراءة العملية الحسابية");return;}}if(a.contains("الحاسبة")||a.contains("حاسبة")){openIntent(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_APP_CALCULATOR),"سأفتح الحاسبة");return;}if(a.contains("الملفات")||a.contains("ملف")){openIntent(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),"سأفتح الملفات");return;}if(a.contains("مشغل")||a.contains("ام اكس")||a.contains("mx")||a.contains("أغنية")||a.contains("اغنية")||a.contains("شغل")){Intent i=getPackageManager().getLaunchIntentForPackage("com.mxtech.videoplayer.ad");if(i==null)i=new Intent(Intent.ACTION_VIEW).setType("audio/*");openIntent(i,"سأفتح مشغل الوسائط");return;}if(a.contains("ثبت")||a.contains("تثبيت")){say("سأفتح ملف التثبيت، وسيطلب أندرويد تأكيدك قبل التثبيت");return;}if(a.contains("الإعدادات")||a.contains("الاعدادات")){openIntent(new Intent(Settings.ACTION_SETTINGS),"سأفتح الإعدادات");return;}say("فهمت الأمر، لكن هذه الوظيفة ستضاف في تحديث قريب");}
 void openIntent(Intent i,String msg){try{startActivity(i);say(msg);}catch(Exception e){say("لا يوجد تطبيق مناسب لهذا الأمر");}}
 double eval(String s){return new Object(){int p=-1,c;void n(){c=++p<s.length()?s.charAt(p):-1;}boolean eat(int x){while(c==' ')n();if(c==x){n();return true;}return false;}double parse(){n();double v=expr();if(p<s.length())throw new RuntimeException();return v;}double expr(){double v=term();for(;;){if(eat('+'))v+=term();else if(eat('-'))v-=term();else return v;}}double term(){double v=factor();for(;;){if(eat('*'))v*=factor();else if(eat('/'))v/=factor();else return v;}}double factor(){if(eat('+'))return factor();if(eat('-'))return -factor();double v;int st=p;if(eat('(')){v=expr();eat(')');}else{while((c>='0'&&c<='9')||c=='.')n();v=Double.parseDouble(s.substring(st,p));}return v;}}.parse();}
 @Override public void onInit(int status){if(status==TextToSpeech.SUCCESS)tts.setLanguage(new Locale("ar"));}
 @Override protected void onDestroy(){if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
